server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/users

        # Product Service
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: productServiceCircuitBreaker
                fallbackUri: forward:/fallback/products

        # Category routes (Product Service)
        - id: category-service
          uri: lb://product-service
          predicates:
            - Path=/api/categories/**
          filters:
            - name: CircuitBreaker
              args:
                name: categoryServiceCircuitBreaker
                fallbackUri: forward:/fallback/categories

        # Inventory Service
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - name: CircuitBreaker
              args:
                name: inventoryServiceCircuitBreaker
                fallbackUri: forward:/fallback/inventory

        # Warehouse (Inventory Service)
        - id: warehouse-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/warehouses/**
          filters:
            - name: CircuitBreaker
              args:
                name: warehouseServiceCircuitBreaker
                fallbackUri: forward:/fallback/warehouses

        # Stock Movements (Inventory Service)
        - id: stock-movement-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/stock-movements/**
          filters:
            - name: CircuitBreaker
              args:
                name: stockMovementServiceCircuitBreaker
                fallbackUri: forward:/fallback/stock-movements

        # Order Service
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderServiceCircuitBreaker
                fallbackUri: forward:/fallback/orders

        # Order Status History (Order Service)
        - id: order-status-history-service
          uri: lb://order-service
          predicates:
            - Path=/api/order-status-history/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderStatusHistoryCircuitBreaker
                fallbackUri: forward:/fallback/order-status-history

        # Payment Service
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentServiceCircuitBreaker
                fallbackUri: forward:/fallback/payments

        # Refunds (Payment Service)
        - id: refund-service
          uri: lb://payment-service
          predicates:
            - Path=/api/refunds/**
          filters:
            - name: CircuitBreaker
              args:
                name: refundServiceCircuitBreaker
                fallbackUri: forward:/fallback/refunds

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: [GET, POST, PUT, DELETE, PATCH, OPTIONS]
            allowedHeaders: "*"
            allowCredentials: false
            maxAge: 3600

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      productServiceCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
      categoryServiceCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
      inventoryServiceCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
      warehouseServiceCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
      stockMovementServiceCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
      orderServiceCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
      orderStatusHistoryCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
      paymentServiceCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
      refundServiceCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.ecommerce.gateway: DEBUG