#spring:
#  application:
#    name: user-service
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true
#    username: root
#    password: Aman@2455
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
#
#server:
#  port: 8081
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#
## ✅ Add to existing application.yml
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html

spring:
  application:
    name: user-service

  datasource:
    # Local default; Railway will override via env
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: ${PORT:8081}
  # Optional; ensures binding to all interfaces in containers/PAAS
  address: 0.0.0.0

eureka:
  client:
    service-url:
      # Railway will set EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    # On Railway we want to advertise the public hostname over HTTPS
    prefer-ip-address: false
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
    instance-id: ${spring.application.name}:${random.value}
# ✅ Add to existing application.yml
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# If you previously disabled discovery in this file, remove those lines:
# spring.cloud.discovery.enabled: false
# eureka.client.enabled: false
