server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: e-commerce-backend-app-production.up.railway.app
    prefer-ip-address: false

  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: true
